apiVersion: v1
kind: Pod
metadata:
  name: alejandro-pod
  labels:
    app: servicio-alejo
spec:
  containers:
    - name: alejandro-container
      image: jesus74/favor-a-alejandro:latest
      ports:
        - containerPort: 3006

---
apiVersion: v1
kind: Service
metadata:
  name: alejandro-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3006
  selector:
    app: servicio-alejo