apiVersion: v1
kind: Pod
metadata:
  name: servicio-cami-pod
  labels:
    app: servicio-cami
spec:
  containers:
    - name: servicio-cami-container
      image: jesus74\favor-a-camilo
      ports:
        - containerPort: 3004


---

apiVersion: v1
kind: Service
metadata:
  name: servicio-cami-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3004
      protocol: TCP
  selector:
    app: servicio-cami