apiVersion: v1
kind: Pod
metadata:
  name: servicio-laura-pod
  labels:
    app: servicio-laura
spec:
  containers:
    - name: servicio-laura-container
      image: criser2013/orquestando-lab:v1
      ports:
        - containerPort: 3001
      resources:
        requests:
          cpu: 1
          memory: "128Mi"
        limits:
          cpu: 2
          memory: "256Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: servicio-laura-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: servicio-laura